# 서울특별시 전체 인구수 데이터

<h1> 서울특별시 어린이 인구수 데티어 전처리 진행 </h1>
  - 데이터 불러오기
    - 서울특별시 전체 인구수 데이터
  - 데이터 확인 및 전처리
    - 전체 인구수 데이터 => 어린이(0세 ~ 13세) 데이터
  - 데이터 저장

## 데이터 불러오기

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
import numpy as np
import pandas as pd

In [21]:
data = pd.read_csv('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_2조/Data/raw data/202112_202112_연령별인구현황_연간.csv', encoding='cp949')

In [22]:
data = data.rename(columns={'2021년_계_총인구수': '2021년 총 인구수',
                            '2021년_계_연령구간인구수': '2021년 어린이 인구수',
                            '2021년_계_0세': '0세',
                            '2021년_계_1세': '1세',
                            '2021년_계_2세': '2세',
                            '2021년_계_3세': '3세',
                            '2021년_계_4세': '4세',
                            '2021년_계_5세': '5세',
                            '2021년_계_6세': '6세',
                            '2021년_계_7세': '7세',
                            '2021년_계_8세': '8세',
                            '2021년_계_9세': '9세',
                            '2021년_계_10세': '10세',
                            '2021년_계_11세': '11세',
                            '2021년_계_12세': '12세',
                            '2021년_계_13세': '13세',
                            })

In [23]:
data['행정구역'] = data['행정구역'].str.strip('서울특별시').str.strip()
data['행정구역'] = data['행정구역'].str[:-13].str.strip()
data['행정구역'][0] = '서울특별시'

In [24]:
data

     행정구역 2021년 총 인구수 2021년 어린이 인구수      0세  ...      9세     10세     11세     12세
0   서울특별시   9,509,458       798,371  43,410  ...  74,480  71,911  72,979  69,798
1     종로구     144,683         9,826     484  ...     961     890   1,016     936
2      중구     122,499         8,088     569  ...     696     656     601     532
3     용산구     222,953        16,745   1,133  ...   1,443   1,384   1,402   1,306
4     성동구     285,990        24,434   1,721  ...   1,981   1,853   1,756   1,603
5     광진구     339,996        24,594   1,353  ...   2,347   2,286   2,340   2,224
6    동대문구     337,400        26,014   1,511  ...   2,309   2,172   2,204   2,048
7     중랑구     387,350        28,394   1,730  ...   2,533   2,452   2,399   2,258
8     성북구     430,528        37,470   1,920  ...   3,488   3,515   3,428   3,201
9     강북구     299,182        19,875     945  ...   1,932   1,887   1,936   1,904
10    도봉구     317,366        23,697   1,108  ...   2,254   2,248   2,255   2,150
11    노원구     510,956        43,819   2,164  ...   4,215   4,214   4,463   4,484
12    은평구     473,307        37,955   2,003  ...   3,576   3,417   3,521   3,362
13   서대문구     304,819        25,229   1,443  ...   2,265   2,087   2,173   2,088
14    마포구     368,905        31,479   1,873  ...   2,861   2,580   2,675   2,563
15    양천구     447,302        43,445   1,755  ...   4,470   4,427   4,751   4,733
16    강서구     574,315        49,126   2,815  ...   4,647   4,404   4,128   3,948
17    구로구     396,754        34,635   2,135  ...   3,060   2,971   2,974   2,723
18    금천구     230,811        15,486     965  ...   1,441   1,288   1,306   1,216
19   영등포구     376,837        31,640   2,193  ...   2,612   2,405   2,345   2,134
20    동작구     385,483        30,709   1,721  ...   2,725   2,584   2,679   2,454
21    관악구     485,699        27,020   1,544  ...   2,426   2,486   2,437   2,254
22    서초구     412,279        45,280   2,018  ...   4,536   4,424   4,677   4,480
23    강남구     533,042        51,721   2,100  ...   5,433   5,499   5,680   5,816
24    송파구     658,338        65,652   3,541  ...   6,087   5,870   5,847   5,562
25    강동구     462,664        46,038   2,666  ...   4,182   3,912   3,986   3,819

[26 rows x 16 columns]

In [25]:
data.to_csv('서울시 어린이 인구 현황.csv')